version: "3.9"
services:
    politicians-parties-api:
        image: ghcr.io/politi-cz/politicz-politicians-and-parties:main
        ports:
            - "5000:80"
            - "5001:443"
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Environment=Development
            - PoliticalPartiesApi_Database__DefaultConnection=${PoliticalPartiesApi_DefaultConnection}
            - PoliticalPartiesApi_Database__MasterConnection=${PoliticalPartiesApi_MasterConnection}
            - PoliticalPartiesApi_Database__Name=${PoliticalPartiesApi_DatabaseName}
            - PoliticalPartiesApi_Auth0__Domain=${PoliticalPartiesApi_Auth0_Domain}
            - PoliticalPartiesApi_Auth0__Audience=${PoliticalPartiesApi_Auth0_Audience}
        depends_on:
            - db
    news-api:
        image: ghcr.io/politi-cz/politicz-news:master
        ports:
            - "5002:80"
            - "5003:443"
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Environment=Development
            - NewsApi_Database__ConnectionString=${NewsApi_ConnectionString}
            - NewsApi_JwtSettings__Authority=${NewsApi_JwtSettings_Authority}
            - NewsApi_JwtSettings__Audience=${NewsApi_JwtSettings_Audience}
        depends_on:
            - db
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Password12345
        ports:
            - "1433:1433"
